#!/usr/bin/env node
/** Anti-aliased twins of the RickyOS 1-bpp icons, for screens drawn into the 16-level frame.
 * Same SVGs and preparation as build_rickyos_app_icons.cjs, build_rickyos_navigation_icons.cjs
 * and build_rickyos_page_icons.cjs, kept as 4-bit coverage instead of a 110 threshold.
 * Run-length coded (byte = (run - 1) << 4 | level) because line icons are mostly empty:
 * a few hundred bytes each instead of 800-1600. Each entry carries an FNV-1a hash of its
 * 1-bpp twin's bytes, which is how the firmware finds it (the 1-bpp arrays are per
 * translation unit, so their addresses cannot be the key).
 * Developer-only dependency: sharp (librsvg).
 * Run: NODE_PATH=/path/to/node_modules node scripts/build_rickyos_aa_icons.cjs
 */
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');

const root = path.resolve(__dirname, '..');
const iconRoot = path.join(root, 'src/components/icons');
const lucide = path.join(root, 'freeink-sdk/libs/assets/Icons/lucide/icons');
const THRESHOLD = 110;

function sized(svg, size) {
  return Buffer.from(svg.replace('<svg ', `<svg width="${size}" height="${size}" `));
}

const sets = [
  ...['transfer', 'opds', 'weread', 'stats', 'gomoku', 'calculator', 'standby'].map(name => ({
    name: `ricky_app_${name}_56`, size: 56,
    svg: () => sized(fs.readFileSync(path.join(iconRoot, 'sources/rickyos/apps', name + '.svg'), 'utf8'), 56),
  })),
  ...['home', 'library', 'apps', 'settings', 'storage'].map(name => ({
    name: `ricky_nav_${name}_40`, size: 40,
    svg: () => sized(fs.readFileSync(path.join(iconRoot, 'sources/rickyos', name + '.svg'), 'utf8'), 40),
  })),
];

// Page icons: read the generator's own table so names and Lucide sources stay in step.
const pageScript = fs.readFileSync(path.join(root, 'scripts/build_rickyos_page_icons.cjs'), 'utf8');
const stroke = pageScript.match(/const STROKE = '?([\d.]+)'?/)[1];
const pageIcons = [...pageScript.matchAll(/\['(\w+)',\s*'([\w-]+)'/g)].map(m => [m[1], m[2]]);
for (const [alias, lucideName] of pageIcons) {
  sets.push({
    name: `icon_ricky_${alias}_40_bits`, size: 40,
    svg: () => Buffer.from(fs.readFileSync(path.join(lucide, lucideName + '.svg'), 'utf8')
      .replace('stroke-width="2"', `stroke-width="${stroke}"`)
      .replace(/width="24"\s+height="24"/, 'width="40" height="40"')),
  });
}

function fnv1a(bytes) {
  let hash = 0x811c9dc5;
  for (const b of bytes) hash = Math.imul(hash ^ b, 0x01000193) >>> 0;
  return hash;
}

async function main() {
  const out = ['#pragma once', '', '#include <cstdint>', '',
    '// Generated by scripts/build_rickyos_aa_icons.cjs. Do not edit.',
    '// 4-bit coverage (0 = paper, 15 = full ink), run-length coded: byte = (run - 1) << 4 | level.', '',
    'namespace ricky_aa_icons {', '',
    'struct Icon {', '  uint32_t bitsHash;  // FNV-1a of the 1-bpp twin', '  uint16_t width;', '  uint16_t height;',
    '  const uint8_t* rle;', '  uint16_t rleBytes;', '};', ''];
  const entries = [];
  let total = 0;
  for (const set of sets) {
    const { data, info } = await sharp(set.svg()).flatten({ background: '#fff' })
      .greyscale().raw().toBuffer({ resolveWithObject: true });
    if (info.channels !== 1 || info.width !== set.size || info.height !== set.size) throw new Error(`${set.name}: bad raster`);
    // The 1-bpp twin, exactly as its own generator writes it.
    const rowBytes = Math.ceil(set.size / 8);
    const bits = Buffer.alloc(rowBytes * set.size, 255);
    for (let y = 0; y < set.size; ++y) for (let x = 0; x < set.size; ++x) {
      if (data[y * set.size + x] < THRESHOLD) bits[y * rowBytes + (x >> 3)] &= ~(0x80 >> (x & 7));
    }
    const rle = [];
    let level = -1, run = 0;
    for (const gray of data) {
      const coverage = Math.round((255 - gray) / 17);
      if (coverage === level && run < 16) { ++run; continue; }
      if (run) rle.push(((run - 1) << 4) | level);
      level = coverage; run = 1;
    }
    rle.push(((run - 1) << 4) | level);
    total += rle.length;
    const id = set.name.replace(/_bits$/, '');
    out.push(`inline constexpr uint8_t k_${id}[] = {`);
    for (let i = 0; i < rle.length; i += 20) {
      out.push('    ' + rle.slice(i, i + 20).map(b => '0x' + b.toString(16).padStart(2, '0').toUpperCase()).join(', ') + ',');
    }
    out.push('};');
    entries.push(`    {0x${fnv1a(bits).toString(16).padStart(8, '0').toUpperCase()}u, ${set.size}, ${set.size}, k_${id}, ${rle.length}},  // ${set.name}`);
  }
  out.push('', 'inline constexpr Icon kIcons[] = {', ...entries, '};', '', '}  // namespace ricky_aa_icons', '');
  fs.writeFileSync(path.join(iconRoot, 'rickyAaIcons.h'), out.join('\n'));
  console.log(`rickyAaIcons.h: ${sets.length} icons, ${total} bytes of coverage`);
}

main().catch(error => { console.error(error); process.exit(1); });
