#!/usr/bin/env python3
"""RickyOS reading-stats mascot (the logo's dog in three moods) -> 1-bpp Flash icons.

Sources: src/components/icons/sources/rickyos/mascot/{sleeping,reading,happy}.png, drawn with
codex image generation from the RickyOS logo. Each is trimmed to its ink, centered on a square,
resized to SIZE and thresholded; light gray fills become paper, outlines and patches stay ink.
Run: python3 scripts/build_rickyos_mascot_icons.py [--out header.h]
"""
import argparse
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "src/components/icons/sources/rickyos/mascot"
NAMES = ("sleeping", "reading", "happy")
SIZE = 150
THRESHOLD = 110


def icon(path: Path) -> bytes:
    gray = Image.open(path).convert("L")
    box = ImageOps.invert(gray).point(lambda v: 255 if v > 60 else 0).getbbox()
    art = gray.crop(box) if box else gray
    side = max(art.size) + 8
    square = Image.new("L", (side, side), 255)
    square.paste(art, ((side - art.width) // 2, (side - art.height) // 2))
    small = square.resize((SIZE, SIZE), Image.LANCZOS)
    row = (SIZE + 7) // 8
    bits = bytearray([0xFF] * (row * SIZE))
    for y in range(SIZE):
        for x in range(SIZE):
            if small.getpixel((x, y)) < THRESHOLD:
                bits[y * row + x // 8] &= ~(0x80 >> (x % 8)) & 0xFF
    return bytes(bits)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "src/components/icons/rickyMascotIcons.h")
    args = parser.parse_args()
    lines = ["#pragma once", "", "#include <cstdint>", "",
             "// Generated by scripts/build_rickyos_mascot_icons.py from sources/rickyos/mascot/*.png.",
             f"// {SIZE} x {SIZE}, MSB-first, 1 = paper, 0 = ink. Regenerate; never edit these bytes.", "",
             f"inline constexpr int kRickyMascotSize = {SIZE};", ""]
    for name in NAMES:
        data = icon(SOURCES / f"{name}.png")
        lines.append(f"static constexpr uint8_t ricky_mascot_{name}[] = {{")
        for offset in range(0, len(data), 19):  # clang-format packs 19 per line
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[offset:offset + 19]) + ",")
        lines += ["};", ""]
    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
