#!/usr/bin/env node
// Encode the USER-SELECTED artwork, not a new design. Developer-only sharp 0.35.4.
// No PNG decoder, SD access, image cache or extra framebuffer on the device.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'src/images/sources/rickyos/approved-logo.png');
const expectedSha = 'ac8c60ca236a864bb2736a2d015222aff2bc2bb667f3d7248c3d9f234863a12f';
const args = process.argv.slice(2);
let output = path.join(root, 'src/images/RickyLogo.h');
let preview;
for (let i = 0; i < args.length; ++i) {
  if (args[i] === '--out' && args[i + 1]) output = path.resolve(args[++i]);
  else if (args[i] === '--preview' && args[i + 1]) preview = path.resolve(args[++i]);
  else throw new Error('Usage: build_rickyos_logo.cjs [--out header.h] [--preview pixels.png]');
}
const width = 384, height = 448, threshold = 128;

async function main() {
  const original = fs.readFileSync(source);
  const sha = crypto.createHash('sha256').update(original).digest('hex');
  if (sha !== expectedSha) throw new Error('Selected artwork hash mismatch; do not silently replace it.');
  const { data, info } = await sharp(original).flatten({ background: '#fff' })
    .greyscale().raw().toBuffer({ resolveWithObject: true });
  if (info.channels !== 1) throw new Error('Expected grayscale image');
  let left = info.width, right = 0, top = info.height, bottom = 0, seed = -1;
  for (let y = 0; y < info.height; ++y) for (let x = 0; x < info.width; ++x) {
    if (data[y * info.width + x] >= threshold) continue;
    if (seed < 0) seed = y * info.width + x; // topmost ink belongs to the enclosing circle
    left = Math.min(left, x); right = Math.max(right, x);
    top = Math.min(top, y); bottom = Math.max(bottom, y);
  }
  if (seed < 0) throw new Error('Empty logo');
  // Isolate its actual connected circle, preserving source edges, not redrawing it.
  const seen = new Uint8Array(data.length), queue = new Int32Array(data.length);
  let head = 0, tail = 1;
  queue[0] = seed; seen[seed] = 1;
  while (head < tail) {
    const point = queue[head++], x = point % info.width, y = Math.floor(point / info.width);
    for (let dy = -1; dy <= 1; ++dy) for (let dx = -1; dx <= 1; ++dx) {
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= info.width || ny >= info.height) continue;
      const next = ny * info.width + nx;
      if (!seen[next] && data[next] < threshold) { seen[next] = 1; queue[tail++] = next; }
    }
  }
  const circle = Buffer.alloc(data.length, 255);
  for (let i = 0; i < tail; ++i) {
    const point = queue[i], x = point % info.width, y = Math.floor(point / info.width);
    for (let dy = -1; dy <= 1; ++dy) for (let dx = -1; dx <= 1; ++dx) {
      const nx = x + dx, ny = y + dy;
      if (nx >= 0 && ny >= 0 && nx < info.width && ny < info.height) {
        const next = ny * info.width + nx; circle[next] = data[next];
      }
    }
  }
  // Technical whitespace crop only. Letterbox, never stretch the selected faces.
  left = Math.max(0, left - 10); top = Math.max(0, top - 10);
  right = Math.min(info.width - 1, right + 10); bottom = Math.min(info.height - 1, bottom + 10);
  const crop = { left, top, width: right - left + 1, height: bottom - top + 1 };
  const scale = Math.min(width / crop.width, height / crop.height);
  const offsetX = Math.floor((width - Math.round(crop.width * scale)) / 2);
  const offsetY = Math.floor((height - Math.round(crop.height * scale)) / 2);
  const personRight = Math.round((660 - left) * scale) + offsetX;
  const wordmarkTop = Math.round((1010 - top) * scale) + offsetY;
  const lines = ['#pragma once', '#include <cstdint>', '',
    '// Generated by scripts/build_rickyos_logo.cjs from the approved artwork; do not edit.',
    `// Source SHA256: ${sha}`, '// Upright MSB-first 1-bpp: 0 = ink, 1 = white/transparent.',
    'namespace RickyLogoAsset {', `inline constexpr int width = ${width}, height = ${height};`,
    `inline constexpr int personRight = ${personRight}, wordmarkTop = ${wordmarkTop};`];
  let fullPacked;
  for (const [name, raw] of [['bits', data], ['circleBits', circle]]) {
    const raster = await sharp(raw, { raw: { width: info.width, height: info.height, channels: 1 } })
      .extract(crop).resize(width, height, { fit: 'contain', background: '#fff' })
      .greyscale().raw().toBuffer();
    if (raster.length !== width * height) throw new Error('Wrong native raster length');
    const packed = Buffer.alloc(width * height / 8, 255);
    for (let p = 0; p < raster.length; ++p) if (raster[p] < threshold) packed[p >> 3] &= ~(0x80 >> (p & 7));
    if (name === 'bits') fullPacked = packed;
    else for (let p = 0; p < packed.length; ++p) packed[p] |= fullPacked[p];
    lines.push(`inline constexpr uint8_t ${name}[] = {`);
    for (let start = 0; start < packed.length; start += 16) {
      lines.push('    ' + [...packed.subarray(start, start + 16)]
        .map(value => '0x' + value.toString(16).padStart(2, '0').toUpperCase()).join(', ') + ',');
    }
    lines.push('};');
    if (name === 'bits' && preview) {
      const pixels = Buffer.from(raster);
      for (let p = 0; p < pixels.length; ++p) pixels[p] = raster[p] < threshold ? 0 : 255;
      await sharp(pixels, { raw: { width, height, channels: 1 } }).png().toFile(preview);
    }
  }
  lines.push('}  // namespace RickyLogoAsset', '');
  fs.writeFileSync(output, lines.join('\n'));
  console.log(`Generated ${output}; 43008 bytes of Flash bitmaps; crop=${JSON.stringify(crop)}; circle pixels=${tail}`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
