#!/usr/bin/env node
/** Lucide SVGs (freeink-sdk submodule) -> 40 px 1-bpp freeink::Icon resources for
 * the RickyOS storage and settings pages and the control center.
 * Developer-only dependency: sharp 0.35.4 (librsvg 2.62.91).
 * Run: NODE_PATH=/path/to/node_modules node scripts/build_rickyos_page_icons.cjs [--out header.h]
 * Lucide's 2 px stroke is thinned to 1.75 (about 2.9 px at 40 px): lighter on
 * e-ink, still solid after thresholding. The checked-in header keeps device and
 * simulator builds independent of Node/sharp.
 */
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const sharp = require('sharp');

const root = path.resolve(__dirname, '..');
const lucide = path.join(root, 'freeink-sdk/libs/assets/Icons/lucide');
const SIZE = 40;
const STROKE = '1.75';
const THRESHOLD = 110;  // Same cut as freeink-sdk gen_icons.py and the navigation icons.
const ICONS = [
  ['storage', 'hard-drive'], ['books', 'book-open'], ['fonts', 'a-large-small'], ['images', 'image'],
  ['downloads', 'download'], ['folder', 'folder-open'], ['upload', 'upload'], ['display', 'sun-moon'],
  ['reader', 'book-open-text'], ['network', 'wifi'], ['power', 'battery-medium'], ['system', 'settings-2'],
  // Control center actions.
  ['night', 'moon'], ['refresh', 'refresh-cw'], ['standby', 'power'], ['transfer', 'arrow-up-down'],
  ['portrait', 'rectangle-vertical'], ['landscape', 'rectangle-horizontal'], ['clean', 'sparkles'],
];

let output = path.join(root, 'src/components/icons/rickyPageIcons.h');
const args = process.argv.slice(2);
for (let i = 0; i < args.length; ++i) {
  if (args[i] === '--out' && args[i + 1]) output = path.resolve(args[++i]);
  else throw new Error('Usage: build_rickyos_page_icons.cjs [--out header.h]');
}

async function main() {
  const commit = execFileSync('git', ['-C', lucide, 'rev-parse', 'HEAD']).toString().trim();
  const lines = ['#pragma once', '', '#include "Icon.h"', '',
    '// Generated by scripts/build_rickyos_page_icons.cjs from Lucide (ISC license),',
    `// commit ${commit}, stroke-width ${STROKE}, ${SIZE} px. Regenerate; never edit these bytes.`, ''];
  for (const [alias, name] of ICONS) {
    const source = fs.readFileSync(path.join(lucide, 'icons', name + '.svg'), 'utf8');
    if (!source.includes('stroke-width="2"')) throw new Error(`${name}: unexpected stroke width`);
    const svg = source.replace('stroke-width="2"', `stroke-width="${STROKE}"`)
      .replace(/width="24"\s+height="24"/, `width="${SIZE}" height="${SIZE}"`);
    const { data, info } = await sharp(Buffer.from(svg)).flatten({ background: '#fff' })
      .greyscale().raw().toBuffer({ resolveWithObject: true });
    if (info.channels !== 1 || info.width !== SIZE || info.height !== SIZE) throw new Error(`${name}: bad raster`);
    const rowBytes = Math.ceil(SIZE / 8);
    const bits = Buffer.alloc(rowBytes * SIZE, 255);
    let inkRows = 0, ink = 0;
    for (let y = 0; y < SIZE; ++y) for (let x = 0; x < SIZE; ++x) {
      if (data[y * SIZE + x] >= THRESHOLD) continue;
      bits[y * rowBytes + (x >> 3)] &= ~(0x80 >> (x & 7));
      inkRows += y;
      ++ink;
    }
    const center = ink ? Math.round(inkRows / ink) : SIZE >> 1;
    lines.push(`// ${alias} (lucide: ${name})`);
    lines.push(`static const uint8_t icon_ricky_${alias}_${SIZE}_bits[] = {`);
    for (let offset = 0; offset < bits.length; offset += 19) {  // clang-format packs 19 per 120-column line
      lines.push('    ' + [...bits.subarray(offset, offset + 19)]
        .map(byte => '0x' + byte.toString(16).padStart(2, '0').toUpperCase()).join(', ') + ',');
    }
    lines.push('};');
    lines.push(`static const freeink::Icon icon_ricky_${alias}_${SIZE} = {${SIZE}, ${SIZE}, ${center}, icon_ricky_${alias}_${SIZE}_bits};`, '');
  }
  fs.writeFileSync(output, lines.join('\n'));
  console.log(`wrote ${output}: ${ICONS.length} icons`);
}

main().catch(error => { console.error(error); process.exit(1); });
