"""Generate src/components/icons/rickyBatteryIcons.h: RickyOS's 32x20 battery.

A thin rounded body with the charge bar inset by a white gap and the cap close to
the body; the charging bolt carries a one-pixel white halo so it reads over both
the bar and the empty cavity. 1-bit, Icon format: a 0 bit is drawn.
"""
from pathlib import Path

W, H = 32, 20
# The bar the firmware fills: x 4..23, y 5..14 (BaseTheme::fillBatteryIcon).
BOLT = ['.....##.', '....##..', '...###..', '..###...', '.#######', '...###..', '..###...', '.###....', '##......']
BOLT_X, BOLT_Y = 10, 6


def rounded(x, y, x0, y0, x1, y1, r):
    cx, cy = x + 0.5, y + 0.5
    left, top, right, bottom = x0, y0, x1 + 1, y1 + 1
    if not (left <= cx <= right and top <= cy <= bottom):
        return False
    nx, ny = min(max(cx, left + r), right - r), min(max(cy, top + r), bottom - r)
    return (cx - nx) ** 2 + (cy - ny) ** 2 <= r * r + 0.01


def body():
    return {(x, y) for y in range(H) for x in range(W)
            if (rounded(x, y, 0, 1, 27, 18, 5) and not rounded(x, y, 2, 3, 25, 16, 3))
            or (x >= 29 and rounded(x, y, 28, 7, 30, 12, 1.5))}


def bolt():
    return {(BOLT_X + c, BOLT_Y + r) for r, row in enumerate(BOLT) for c, ch in enumerate(row) if ch == '#'}


def halo():
    marks = bolt()
    return {(x + dx, y + dy) for x, y in marks for dx in (-1, 0, 1) for dy in (-1, 0, 1)} - marks


def encode(name, marks):
    data = []
    for y in range(H):
        for byte in range(W // 8):
            value = 0xFF
            for bit in range(8):
                if (byte * 8 + bit, y) in marks:
                    value &= ~(0x80 >> bit)
            data.append(value)
    rows = [', '.join(f'0x{v:02X}' for v in data[i:i + 16]) for i in range(0, len(data), 16)]
    return (f'static const uint8_t {name}_bits[] = {{\n    ' + ',\n    '.join(rows) + '};\n'
            f'static const freeink::Icon {name} = {{{W}, {H}, {H // 2}, {name}_bits}};\n')


def header():
    return ('#pragma once\n\n#include "Icon.h"\n\n'
            '// Generated by scripts/gen_ricky_battery_icons.py. Do not edit.\n\n' +
            encode('ricky_battery_body_32x20', body()) + encode('ricky_battery_bolt_32x20', bolt()) +
            encode('ricky_battery_bolt_halo_32x20', halo()))


if __name__ == '__main__':
    root = Path(__file__).resolve().parents[1]
    (root / 'src/components/icons/rickyBatteryIcons.h').write_text(header())
