"""Generate src/components/fonts/rickyClockDigits.h: the Standby clock's large digits.

The firmware's largest face is 18 pt, far too small for a clock that has to carry a
picture. These are Inter Display Light digits and a colon, rasterised once at the size
the Standby layout draws them, as 4-bit coverage (0 = paper, 15 = full ink) for the
16-gray Standby frame. Digits sit centred in one cell width so the minutes do not
shift sideways as they change.

Inter is under the SIL Open Font License 1.1 (LICENSE alongside the font):
https://github.com/rsms/inter
"""
import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CHARS = '0123456789:'
SUPERSAMPLE = 4


def render(font_path, cap_height):
    # Size the face so the digits' cap height lands on cap_height pixels.
    probe = ImageFont.truetype(str(font_path), 1000)
    top, bottom = probe.getbbox('0')[1], probe.getbbox('0')[3]
    size = round(cap_height * 1000 / (bottom - top))
    font = ImageFont.truetype(str(font_path), size * SUPERSAMPLE)
    ascent_top = font.getbbox('0')[1]
    cell = max(font.getlength(c) for c in '0123456789') / SUPERSAMPLE
    glyphs = {}
    for ch in CHARS:
        left, gtop, right, gbottom = font.getbbox(ch)
        w = (right - left + SUPERSAMPLE - 1) // SUPERSAMPLE + 1
        h = (gbottom - ascent_top + SUPERSAMPLE - 1) // SUPERSAMPLE + 1
        big = Image.new('L', (w * SUPERSAMPLE, h * SUPERSAMPLE), 0)
        ImageDraw.Draw(big).text((-left, -ascent_top), ch, font=font, fill=255)
        small = big.resize((w, h), Image.BOX)
        levels = [round(p / 17) for p in small.tobytes()]
        advance = font.getlength(ch) / SUPERSAMPLE
        glyphs[ch] = dict(w=w, h=h, x=round(left / SUPERSAMPLE), advance=advance, levels=levels)
    return round(cell), glyphs


def header(cap_height, cell, glyphs):
    out = ['#pragma once', '', '#include <cstdint>', '',
           '// Generated by scripts/gen_ricky_clock_digits.py. Do not edit.',
           '// Inter Display Light (SIL Open Font License 1.1), 4-bit coverage, high nibble first.',
           '', 'namespace ricky_clock_digits {', '',
           f'constexpr int kCapHeight = {cap_height};', f'constexpr int kCellWidth = {cell};', '',
           'struct Glyph {', '  char ch;', '  int16_t width;', '  int16_t height;', '  int16_t left;',
           '  int16_t advance;', '  const uint8_t* bits;', '};', '']
    for ch, g in glyphs.items():
        name = 'colon' if ch == ':' else f'd{ch}'
        packed = []
        for y in range(g['h']):
            row = g['levels'][y * g['w']:(y + 1) * g['w']]
            row += [0] * (len(row) % 2)
            packed += [(row[i] << 4) | row[i + 1] for i in range(0, len(row), 2)]
        lines = [', '.join(f'0x{b:02X}' for b in packed[i:i + 20]) for i in range(0, len(packed), 20)]
        out.append(f'inline constexpr uint8_t k_{name}[] = {{\n    ' + ',\n    '.join(lines) + '};')
    out.append('')
    out.append('inline constexpr Glyph kGlyphs[] = {')
    for ch, g in glyphs.items():
        name = 'colon' if ch == ':' else f'd{ch}'
        out.append(f"    {{'{ch}', {g['w']}, {g['h']}, {g['x']}, {round(g['advance'])}, k_{name}}},")
    out += ['};', '', '}  // namespace ricky_clock_digits', '']
    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--font', default=str(ROOT / 'scripts/fonts/InterDisplay-Light.ttf'))
    parser.add_argument('--cap-height', type=int, default=112)
    args = parser.parse_args()
    cell, glyphs = render(Path(args.font), args.cap_height)
    target = ROOT / 'src/components/fonts/rickyClockDigits.h'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(header(args.cap_height, cell, glyphs))
    print(f'{target}: cell {cell}px, {sum(len(g["levels"]) for g in glyphs.values()) // 2} bytes')


if __name__ == '__main__':
    main()
